CREATE TABLE CIUDAD
(ID_CIUDAD VARCHAR2 (5) NOT NULL,
NOMBRE	VARCHAR2(15) NOT NULL,
ESTADO	VARCHAR2(15),
PAIS	VARCHAR(30),
PRIMARY	KEY(ID_CIUDAD));

--Inserta datos a la tabla para realizar pruebas
INSERT INTO CIUDAD VALUES ('CDAD1', 'Cali', 'Disponible', 'Colombia');

CREATE	TABLE	AEROPUERTO
(ID_AEROPUERTO VARCHAR2(3) NOT NULL,
NOMBRE	VARCHAR2(100)	NOT	NULL,
ESTADO	VARCHAR2(15),	
PAIS	VARCHAR(30),
ID_CIUDAD	VARCHAR2 (5),
PRIMARY	KEY(ID_AEROPUERTO),
FOREIGN	KEY(ID_CIUDAD)	REFERENCES	CIUDAD(ID_CIUDAD)	ON	DELETE	CASCADE);

--Inserta un aeropuerto como prueba, el ID_CIUDAD debe ser el de una ciudad que se haya creado en la tabla CIUDAD porque sino muestra error
INSERT INTO AEROPUERTO VALUES ('AP1', 'El dorado Bogota', 'Disponible', 'Colombia', 'CDAD1');

CREATE TABLE	AEROLINEA
(ID_AEROLINEA VARCHAR(2) NOT NULL,
NOMBRE	VARCHAR2(50),
CODIGO_TRES_DIGITOS	VARCHAR(3),
PRIMARY	KEY(ID_AEROLINEA));

--Inserta Aerolínea de prueba, muestra error pero guarda
INSERT INTO AEROLINEA VALUES ('AA', 'American Airlines', 'AAL');

CREATE	TABLE AEROPUERTO_AEROLINEA
(ID_AEROLINEA  VARCHAR(2) NOT NULL,
ID_AEROPUERTO VARCHAR(3) NOT NULL,
PRIMARY	KEY(ID_AEROLINEA, ID_AEROPUERTO),
FOREIGN	KEY(ID_AEROLINEA)	REFERENCES	AEROLINEA(ID_AEROLINEA)	ON	DELETE	CASCADE,
FOREIGN	KEY(ID_AEROPUERTO)	REFERENCES	AEROPUERTO(ID_AEROPUERTO)	ON	DELETE	CASCADE);

--Relaciona la Aerolínea y Aeropuerto creados anteriormente
INSERT INTO AEROPUERTO_AEROLINEA VALUES ('AA', 'AP1');







CREATE TABLE USUARIOS
   (	ID_USUARIO NUMBER NOT NULL ENABLE, 
	USUARIO VARCHAR2(20 BYTE), 
	PASSWORD VARCHAR2(100 BYTE), 
	CORREO_ELECTRONICO VARCHAR2(20 BYTE), 
	 CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO));

CREATE TABLE ROLES
   (ID_ROL NUMBER NOT NULL ENABLE, 
	NOMBRE VARCHAR2(20 BYTE), 
	 CONSTRAINT ROLES_PK PRIMARY KEY (ID_ROL));

CREATE TABLE ROLES_USUARIOS
   (	ID_USUARIO NUMBER, 
	ID_ROL NUMBER, 
	NOMBRE VARCHAR2(20 BYTE));

CREATE	TABLE VUELO
(ID_VUELO	NUMBER	NOT	NULL,
FUENTE	VARCHAR(3),
DESTINO	VARCHAR(3),
LLEGADA	VARCHAR2(10),
SALIDA	VARCHAR2(10),
ESTADO	VARCHAR(10),
DURACION	VARCHAR2(30),
TIPO_VUELO	VARCHAR(10),
NUMERO_PARADAS	NUMBER,
ID_AEROLINEA	NUMBER,
PRIMARY	KEY(ID_VUELO),
FOREIGN	KEY(ID_AEROLINEA)	REFERENCES	AEROLINEA(ID_AEROLINEA)	ON	DELETE	CASCADE);

CREATE	TABLE	PASAJERO
(ID_PASAJERO	NUMBER	NOT	NULL,
ID_VUELO NUMBER,
NUMERO_PASAPORTE	VARCHAR(10)	NOT	NULL,
NOMBRES VARCHAR(40),
APELLIDOS VARCHAR(40),
GENERO VARCHAR(40),
DIRECCION VARCHAR(40),
TELEFONO NUMBER,
EDAD NUMBER,
PRIMARY	KEY(ID_PASAJERO,	NUMERO_PASAPORTE),
FOREIGN	KEY(ID_VUELO)	REFERENCES	VUELO(ID_VUELO)	ON	DELETE	CASCADE);

CREATE	TABLE	EMPLEADO
(ID_EMPLEADO	NUMBER	NOT	NULL,
NOMBRES	VARCHAR2(30),
APELLIDOS	VARCHAR(30),
DIRECCION	VARCHAR2(100),
TELEFONO	NUMBER,
EDAD	NUMBER,
GENERO	VARCHAR(1),
CARGO	VARCHAR2(30),
ID_AEROPUERTO	NUMBER,
PRIMARY	KEY(ID_EMPLEADO),
FOREIGN	KEY(ID_AEROPUERTO)	REFERENCES	AEROPUERTO(ID_AEROPUERTO)	ON	DELETE	CASCADE);

CREATE	TABLE	BOLETO
(ID_BOLETO	NUMBER	NOT	NULL,
ID_PASAJERO	NUMBER,
FUENTE	VARCHAR(3),
DESTINO	VARCHAR(3),
FECHA_RESERVA	DATE,
FECHA_VIAJE	DATE,
NUMERO_ASIENTO	VARCHAR(5),
CLASE	VARCHAR2(15),
FECHA_CANCELACION	DATE,
NUMERO_PASAPORTE VARCHAR(10),
PRIMARY	KEY(ID_BOLETO),
FOREIGN	KEY(ID_PASAJERO,	NUMERO_PASAPORTE)	REFERENCES	PASAJERO(ID_PASAJERO,	NUMERO_PASAPORTE)	ON	DELETE	CASCADE);

















